-- ============================================================================
-- Dogedin — directory expansion seed (run AFTER schema.sql, safe to re-run)
-- ----------------------------------------------------------------------------
-- Real, researched dog businesses and dog-friendly places across the town ring:
-- Dunedin, Clearwater, Palm Harbor and Tarpon Springs. Every entry was
-- verified against its official website / county parks page at import time
-- (July 2026): names, addresses, phones and dog policies. Descriptions are
-- original copy written for Dogedin, not scraped text.
--
-- Design choices, deliberately:
--   * status 'approved' — these are directory listings, not submissions; they
--     go straight into the guide. Edit or remove any of them at
--     /admin/businesses like any other listing.
--   * NO seeded reviews — reviews belong to the community. Fake ones would
--     poison the review-driven ordering (and trust).
--   * images are category placeholder cards (/assets/spots/cat-*.svg) in the
--     site's house style. When a business claims its listing it can replace
--     the placeholder with a real photo via the usual channels.
--   * owner_name/owner_email stay null until an owner claims the listing —
--     the phone/website here are the public storefront contacts, which is
--     also your outreach list (see /admin/businesses).
--   * on conflict (slug) do nothing — re-running never duplicates and never
--     overwrites edits you've made since.
-- ============================================================================

insert into public.businesses
  (slug, name, category, city, neighborhood, description, image, dog_friendly,
   phone, website, address, status)
values
  ('animal-hospital-of-dunedin', 'Animal Hospital of Dunedin', 'Vet', 'Dunedin', null, 'A full-service veterinary practice caring for Dunedin''s dogs and cats since 1977, with wellness visits, dentistry, surgery, and in-house diagnostics. Weekend hours make it easy to fit checkups around beach days with your pup.', '/assets/spots/cat-vet.svg', true, '(727) 733-9351', 'https://www.ahofd.com/', '1355 Pinehurst Rd, Dunedin, FL 34698', 'approved'),
  ('dunedin-animal-medical-center-pet-resort', 'Dunedin Animal Medical Center & Pet Resort', 'Vet', 'Dunedin', null, 'A Main Street veterinary hospital open seven days a week, pairing medical care with an on-site pet resort for boarding. Handy for travelers who need a vet visit and a safe place for their dog in one stop.', '/assets/spots/cat-vet.svg', true, '(727) 738-2273', 'https://dunedinamc.com/', '1546 Main St, Dunedin, FL 34698', 'approved'),
  ('paws-and-claws-animal-medical-center', 'Paws and Claws Animal Medical Center', 'Vet', 'Dunedin', 'Downtown Dunedin', 'A close-knit small-animal practice just off downtown Dunedin that treats dogs and cats along with rabbits, birds, and other pocket pets. The small team gives visits a personal, neighborly feel.', '/assets/spots/cat-vet.svg', true, '(727) 953-6588', 'https://pawsandclawsanimalcenter.com/', '812 Louden Ave, Dunedin, FL 34698', 'approved'),
  ('woof-gang-bakery-grooming-dunedin', 'Woof Gang Bakery & Grooming Dunedin', 'Groomer', 'Dunedin', null, 'A grooming spa and pet boutique where dogs can get a full cage-free groom, then sniff out fresh-baked treats and natural food on the way out. Open seven days a week for pre-adventure spruce-ups.', '/assets/spots/cat-groomer.svg', true, '(727) 474-3000', 'https://woofgangdunedin.com/', '818 Highland Ave, Dunedin, FL 34698', 'approved'),
  ('polly-s-pet-grooming', 'Polly''s Pet Grooming', 'Groomer', 'Dunedin', null, 'A homegrown Dunedin grooming shop offering full-service cuts, de-shedding, nail trims, and ear cleaning for dogs of all sizes. A reliable local pick for keeping sandy beach dogs fresh.', '/assets/spots/cat-groomer.svg', true, '(727) 403-1846', 'http://pollyspetgrooming.com/', '230 Patricia Ave, Dunedin, FL 34698', 'approved'),
  ('dunedin-pet-supply', 'Dunedin Pet Supply', 'Retail / Shop', 'Dunedin', 'Downtown Dunedin', 'A locally owned natural pet store on Main Street stocking quality food, treats, and chews from small Florida makers. Dogs are welcome inside, and a self-serve dog wash handles post-park cleanup.', '/assets/spots/cat-shop.svg', true, '(727) 601-4661', 'https://dunedinpetsupply.com/', '1045 Main St, Dunedin, FL 34698', 'approved'),
  ('hog-island-fish-camp', 'Hog Island Fish Camp', 'Restaurant', 'Dunedin', 'Downtown Dunedin', 'A laid-back seafood spot serving local grouper, hogfish, and Southern sides, with leashed dogs welcome on the covered front patio. They even keep a dedicated dog menu so your pup can order too.', '/assets/spots/cat-restaurant.svg', true, '(727) 736-1179', 'https://www.hogislandfishcamp.com/', '900 Broadway, Dunedin, FL 34698', 'approved'),
  ('the-living-room-on-main', 'The Living Room on Main', 'Restaurant', 'Dunedin', 'Downtown Dunedin', 'An upscale-casual New American eatery in the heart of downtown Dunedin where dogs are welcome to join you at the outdoor tables. A good pick when you want a nicer dinner without leaving your pup at home.', '/assets/spots/cat-restaurant.svg', true, '(727) 736-5202', null, '487 Main St, Dunedin, FL 34698', 'approved'),
  ('the-honu-restaurant-tiki-bar', 'The Honu Restaurant & Tiki Bar', 'Restaurant', 'Dunedin', 'Downtown Dunedin', 'Downtown Dunedin''s Polynesian restaurant and tiki bar, pouring tropical rum drinks alongside Hawaiian-inspired plates. Pups are welcome in the outdoor area and can nibble from a dog menu of their own.', '/assets/spots/cat-restaurant.svg', true, '(727) 333-7777', 'https://thehonurestaurant.com/', '516 Grant St, Dunedin, FL 34698', 'approved'),
  ('cueni-brewing-co', 'Cueni Brewing Co.', 'Brewery / Bar', 'Dunedin', null, 'A small craft brewery a short stroll from downtown, known for welcoming canine regulars on its canopy-shaded patio. Grab a house-brewed pint while your dog lounges in the shade.', '/assets/spots/cat-brewery.svg', true, '(727) 266-4102', 'https://cuenibrewing.com/', '945 Huntley Ave, Dunedin, FL 34698', 'approved'),
  ('dog-pub-social', 'Dog Pub Social', 'Brewery / Bar', 'Dunedin', null, 'Dunedin''s off-leash dog park and bar combo, with turf play yards, puppy pools, double-gated entries, and staff ''Rufferees'' watching over playtime. Humans sip drinks while vaccinated, fixed pups romp free.', '/assets/spots/cat-brewery.svg', true, null, 'https://dogpubsocial.com/', '1260 Main St, Dunedin, FL 34698', 'approved'),
  ('weaver-park', 'Weaver Park', 'Park / Trail', 'Dunedin', null, 'A waterfront city park on St. Joseph Sound with a fishing pier, shade trees, and direct access to the Pinellas Trail. Leashed dogs (6-foot leash) are welcome to join the stroll along the water.', '/assets/spots/cat-park.svg', true, null, 'https://www.dunedin.gov/Activities-and-Recreation/Parks-Recreation/Parks-Playgrounds/Weaver-Park', '1258 Bayshore Blvd, Dunedin, FL 34698', 'approved'),
  ('edgewater-park', 'Edgewater Park', 'Park / Trail', 'Dunedin', 'Downtown Dunedin', 'A shady four-acre park at the Dunedin Marina where Main Street meets the water, perfect for sunset watching with a leashed pup. Its lawns and gazebo sit steps from downtown''s dog-friendly patios.', '/assets/spots/cat-park.svg', true, null, 'https://www.dunedin.gov/Community/Parks-Recreation/Parks-Playgrounds/Edgewater-Park', '51 Main St, Dunedin, FL 34698', 'approved'),
  ('fred-marquis-pinellas-trail-dunedin-segment', 'Fred Marquis Pinellas Trail (Dunedin segment)', 'Park / Trail', 'Dunedin', 'Downtown Dunedin', 'The famous 47-mile rail-trail runs straight through downtown Dunedin, passing shops, restaurants, and waterfront parks. Leashed dogs are welcome, and the downtown stretch is lined with pup-friendly pit stops.', '/assets/spots/cat-park.svg', true, null, 'https://pinellas.gov/pinellas-county-trail-guide/', null, 'approved'),
  ('animal-health-care-clinic', 'Animal Health Care Clinic', 'Vet', 'Clearwater', null, 'A long-standing Drew Street veterinary hospital providing wellness exams, surgery, and dental care for Clearwater dogs and cats. A dependable mid-town option for both routine and sick visits.', '/assets/spots/cat-vet.svg', true, '(727) 446-5501', 'https://animalhealthcareclinic.com/', '2118 Drew St, Clearwater, FL 33765', 'approved'),
  ('belcher-animal-hospital', 'Belcher Animal Hospital', 'Vet', 'Clearwater', null, 'A full-service animal hospital on South Belcher Road offering preventive care, diagnostics, and surgery. A convenient choice for families on the Clearwater-Largo line.', '/assets/spots/cat-vet.svg', true, '(727) 536-6548', 'https://belcheranimalhospital.com/', '1432 S Belcher Rd, Clearwater, FL 33764', 'approved'),
  ('veterinary-medical-hospital-of-clearwater', 'Veterinary Medical Hospital of Clearwater', 'Vet', 'Clearwater', 'Countryside', 'A veterinary hospital in the Countryside area handling everything from puppy checkups to Saturday sick visits. Its six-day schedule makes it easy to squeeze in care for busy dog households.', '/assets/spots/cat-vet.svg', true, '(727) 796-1026', 'https://clearwateranimalhospital.com/', '2420 State Road 580, Clearwater, FL 33761', 'approved'),
  ('harborside-animal-hospital', 'Harborside Animal Hospital', 'Vet', 'Clearwater', null, 'A compassionate neighborhood practice on McMullen Booth Road near Safety Harbor, offering wellness, dental, and general medical care for dogs and cats. Known for a personal touch with nervous pups.', '/assets/spots/cat-vet.svg', true, '(727) 726-1616', 'https://harborsideanimalhospital.com/', '1590 N McMullen Booth Rd, Suite K5, Clearwater, FL 33759', 'approved'),
  ('the-pawfectionist-dog-salon', 'The Pawfectionist Dog Salon', 'Groomer', 'Clearwater', 'Countryside', 'An appointment-only grooming salon in north Clearwater where each dog gets unhurried, one-on-one attention. Full grooms, baths, and tidy-ups without the big-box bustle.', '/assets/spots/cat-groomer.svg', true, '(727) 486-2534', 'https://www.pawfectionistdogsalon.com/', '29817 US Hwy 19 N, Clearwater, FL 33761', 'approved'),
  ('the-hairy-hound', 'The Hairy Hound', 'Groomer', 'Clearwater', null, 'A well-reviewed professional grooming shop offering haircuts, hydro-spa baths, brush-outs, and nail trims Tuesday through Saturday. Regulars praise the gentle, skilled groomers.', '/assets/spots/cat-groomer.svg', true, '(727) 449-0110', 'https://thehairyhound.com/', '1905 N Hercules Ave, Clearwater, FL 33763', 'approved'),
  ('pet-safari', 'Pet Safari', 'Retail / Shop', 'Clearwater', null, 'A family-owned pet store serving Clearwater since the early 1970s, with quality food and supplies plus in-store dog and cat grooming. A true local institution for pet families.', '/assets/spots/cat-shop.svg', true, '(727) 443-0993', 'https://petsafari.com/', '1577 S Highland Ave, Clearwater, FL 33756', 'approved'),
  ('fluffy-puppies-of-pinellas', 'Fluffy Puppies of Pinellas', 'Retail / Shop', 'Clearwater', null, 'A neighborhood dog store on Fort Harrison Avenue that has specialized in USA-made food, treats, and supplements since 2005. Bring your pup along to pick out their own snacks.', '/assets/spots/cat-shop.svg', true, '(727) 446-7999', 'https://fluffypuppiespinellas.com/', '1447 S Fort Harrison Ave, Clearwater, FL 33756', 'approved'),
  ('salt-cracker-fish-camp', 'Salt Cracker Fish Camp', 'Restaurant', 'Clearwater', 'Clearwater Beach', 'A casual seafood joint at the Clearwater Beach Marina serving po'' boys, fresh catch, and an all-day happy hour. Dogs are welcome at the outdoor tables with front-row views of the boats.', '/assets/spots/cat-restaurant.svg', true, '(727) 442-6910', 'https://www.saltcrackerfishcamp.com/', '25 Causeway Blvd, Clearwater, FL 33767', 'approved'),
  ('the-bait-house-tackle-tavern', 'The Bait House Tackle & Tavern', 'Restaurant', 'Clearwater', 'Clearwater Beach', 'Part bait shop, part waterfront tavern at the base of the Memorial Causeway, slinging fresh seafood right on the marina. Leashed dogs are welcome on the open-air deck over the water.', '/assets/spots/cat-restaurant.svg', true, '(727) 446-8134', 'https://www.clearwaterbaithouse.com/', '45 Causeway Blvd, Clearwater, FL 33767', 'approved'),
  ('crabby-s-dockside', 'Crabby''s Dockside', 'Restaurant', 'Clearwater', 'Clearwater Beach', 'A lively two-story seafood restaurant overlooking the Clearwater Beach Marina, famous for crab and waterfront sunsets. Dogs are welcome on the first-floor outdoor patio.', '/assets/spots/cat-restaurant.svg', true, '(727) 210-1313', 'https://crabbysdocksideclearwater.com/', '37 Causeway Blvd, Clearwater Beach, FL 33767', 'approved'),
  ('clear-sky-beachside-cafe', 'Clear Sky Beachside Cafe', 'Cafe', 'Clearwater', 'Clearwater Beach', 'A beloved all-day cafe half a block from the sand on Mandalay Avenue, serving breakfast through dinner with globally inspired flavors. The outdoor seating happily hosts four-legged beachgoers.', '/assets/spots/cat-cafe.svg', true, '(727) 442-3684', 'https://clearskyrestaurants.com/cafe/', '490 Mandalay Ave, Clearwater Beach, FL 33767', 'approved'),
  ('frenchy-s-saltwater-cafe', 'Frenchy''s Saltwater Cafe', 'Restaurant', 'Clearwater', 'Clearwater Beach', 'A Clearwater Beach classic from the Frenchy''s family, known for grouper sandwiches and she-crab soup. Dogs get a warm welcome and water bowls in the outdoor seating area.', '/assets/spots/cat-restaurant.svg', true, '(727) 461-6295', 'https://frenchysonline.com/', '419 Poinsettia Ave, Clearwater Beach, FL 33767', 'approved'),
  ('crest-lake-dog-park', 'Crest Lake Dog Park', 'Park / Trail', 'Clearwater', null, 'A fenced, three-acre off-leash facility inside Crest Lake Park with separate yards by dog size, drinking fountains, and paw-wash stations. Leashed pups can also loop the shaded path around the lake.', '/assets/spots/cat-park.svg', true, null, 'https://www.myclearwater.com/Neighborhood-Map-Locations/Parks-Trails-and-Recreation-Centers/Crest-Lake-Park', '332 S Glenwood Ave, Clearwater, FL 33756', 'approved'),
  ('enterprise-dog-park', 'Enterprise Dog Park', 'Park / Trail', 'Clearwater', 'Countryside', 'One of the area''s biggest dog parks at over 20 acres, with wide-open off-leash sections, looped gravel trails, rinse stations, and plenty of water fountains. Room to truly run, even for high-energy breeds.', '/assets/spots/cat-park.svg', true, '(727) 562-4800', 'https://www.myclearwater.com/Neighborhood-Map-Locations/Parks-Trails-and-Recreation-Centers/Enterprise-Dog-Park', '2671 Enterprise Rd E, Clearwater, FL 33761', 'approved'),
  ('sand-key-park-paw-playground', 'Sand Key Park Paw Playground', 'Park / Trail', 'Clearwater', 'Sand Key', 'A fenced off-leash dog area inside beautiful Sand Key Park, just across the bridge from Clearwater Beach, with separate small and large dog sides and watering stations. Salt air and shade make it a favorite cooldown spot.', '/assets/spots/cat-park.svg', true, '(727) 582-2100', 'https://pinellas.gov/parks/sand-key-park/', '1060 Gulf Blvd, Clearwater, FL 33767', 'approved'),
  ('tlc-animal-hospital', 'TLC Animal Hospital', 'Vet', 'Palm Harbor', null, 'A longtime Palm Harbor practice with more than 35 years in the community, handling everything from wellness exams to surgery and in-house diagnostics. A dependable first call for keeping your pup healthy year-round.', '/assets/spots/cat-vet.svg', true, '(727) 787-3110', 'https://www.tlcanimalhospital.us/', '270 Palm Harbor Blvd, Palm Harbor, FL 34683', 'approved'),
  ('palm-harbor-animal-hospital', 'Palm Harbor Animal Hospital', 'Vet', 'Palm Harbor', null, 'Locally and independently owned, this clinic has cared for Palm Harbor dogs and cats for over four decades. Expect a small-practice feel where the staff tends to know regulars by name.', '/assets/spots/cat-vet.svg', true, '(727) 785-1010', 'https://palmharboranimalhospital.com/', '36342 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('animal-and-bird-medical-center-of-palm-harbor', 'Animal and Bird Medical Center of Palm Harbor', 'Vet', 'Palm Harbor', null, 'A full-service hospital that treats dogs and cats alongside birds, pocket pets, and exotics. Handy for multi-pet households that want one vet for the whole crew.', '/assets/spots/cat-vet.svg', true, '(727) 784-0558', 'https://dogcatbirdvet.org/', '35080 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('country-oaks-animal-hospital-boarding-kennel', 'Country Oaks Animal Hospital & Boarding Kennel', 'Vet', 'Palm Harbor', null, 'Veterinary care and an on-site boarding kennel under one roof, which makes vacation logistics easier for dog owners. A quieter Belcher Road location away from the US 19 rush.', '/assets/spots/cat-vet.svg', true, '(727) 785-6524', 'https://www.countryoaksanimalhospital.com/', '1412 Belcher Rd, Palm Harbor, FL 34683', 'approved'),
  ('pupperazi-pet-spa', 'Pupperazi Pet Spa', 'Groomer', 'Palm Harbor', null, 'A boutique grooming salon on Tampa Road offering baths, haircuts, and nail trims with a spa-day vibe. Closed Sundays and Mondays, so plan your pup''s glow-up midweek.', '/assets/spots/cat-groomer.svg', true, '(727) 753-9302', 'https://www.pupperazipetspa.com/', '3454 Tampa Rd, Palm Harbor, FL 34684', 'approved'),
  ('a-pet-spa-grooming', 'A Pet Spa Grooming', 'Groomer', 'Palm Harbor', null, 'A boutique dog and cat grooming spa in the Fountains Shopping Center where pets are treated like family. Full grooms, tidy-ups, and nail care in a calm setting.', '/assets/spots/cat-groomer.svg', true, '(727) 329-9000', 'https://www.petspagrooming.com/', '34738 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('palm-harbor-pet-grooming', 'Palm Harbor Pet Grooming', 'Groomer', 'Palm Harbor', null, 'A straightforward, well-reviewed neighborhood groomer handling dogs and cats of all sizes. Good for regular maintenance clips without the big-box wait.', '/assets/spots/cat-groomer.svg', true, '(727) 786-8290', 'https://www.palmharborpetgrooming.com/', '31944 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('pet-supermarket-palm-harbor', 'Pet Supermarket Palm Harbor', 'Retail / Shop', 'Palm Harbor', null, 'A stocked-up stop for food, treats, toys, and gear, and leashed dogs are welcome to browse the aisles with you. A quick errand your dog will think is an outing.', '/assets/spots/cat-shop.svg', true, '(727) 784-9306', 'https://www.petsupermarket.com/storelocator/?storeId=149', '32560 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('petco-palm-harbor', 'Petco Palm Harbor', 'Retail / Shop', 'Palm Harbor', null, 'Full-line pet supply store at US 19 and Curlew Road with grooming, dog training classes, and vaccination clinics on site. Leashed dogs are always welcome inside.', '/assets/spots/cat-shop.svg', true, '(727) 785-8263', 'https://stores.petco.com/fl/palm-harbor/pet-supplies-palmharbor-fl-1525.html', '30697 US Highway 19 N, Palm Harbor, FL 34684', 'approved'),
  ('de-bine-brewing-co', 'de Bine Brewing Co.', 'Brewery / Bar', 'Palm Harbor', 'Downtown Palm Harbor', 'A craft brewery in downtown Palm Harbor where dogs are welcome on the back patio and at the barrel high-tops alongside rotating food trucks. Pups stay outside the taproom, but the outdoor hangout is the best seat anyway.', '/assets/spots/cat-brewery.svg', true, '(727) 233-7964', 'https://www.debinebrewingco.com/', '993 Florida Ave, Palm Harbor, FL 34683', 'approved'),
  ('stilt-house-brewery', 'Stilt House Brewery', 'Brewery / Bar', 'Palm Harbor', 'Downtown Palm Harbor', 'A laid-back, dog-friendly brewery right off the Pinellas Trail pouring 20-plus house-brewed beers. Perfect finish line for a trail walk with your dog in tow.', '/assets/spots/cat-brewery.svg', true, '(727) 270-7373', 'https://www.stilthousebrewery.com/', '625 US Highway 19 Alt, Palm Harbor, FL 34683', 'approved'),
  ('the-thirsty-marlin', 'The Thirsty Marlin', 'Restaurant', 'Palm Harbor', 'Downtown Palm Harbor', 'A downtown Palm Harbor seafood staple where leashed dogs can join you at the front patio tables. Fresh catch, cold drinks, and a steady parade of neighborhood pups.', '/assets/spots/cat-restaurant.svg', true, '(727) 784-3469', 'https://thirstymarlin.com/', '1023 Florida Ave, Palm Harbor, FL 34683', 'approved'),
  ('the-ozona-pig', 'The Ozona Pig', 'Restaurant', 'Palm Harbor', 'Ozona', 'A beloved Ozona barbecue joint serving Memphis-style pulled pork, brisket, and ribs, with pet-friendly outdoor tables. The smoky smells alone will make your dog''s day.', '/assets/spots/cat-restaurant.svg', true, '(727) 773-0744', 'https://theozonapig.com/', '311 Orange St, Palm Harbor, FL 34683', 'approved'),
  ('paw-playground-at-john-chesnut-sr-park', 'Paw Playground at John Chesnut Sr. Park', 'Park / Trail', 'Palm Harbor', 'East Lake', 'A 1.5-acre off-leash dog park inside John Chesnut Sr. Park on Lake Tarpon, with separate fenced areas for large and small dogs, kiddie pools, water stations, and shade. Free entry and parking make it an easy regular outing.', '/assets/spots/cat-park.svg', true, '(727) 582-2100', 'https://pinellas.gov/parks/john-chesnut-sr-park/', '2200 East Lake Rd S, Palm Harbor, FL 34685', 'approved'),
  ('wall-springs-park', 'Wall Springs Park', 'Park / Trail', 'Palm Harbor', null, 'A 210-acre coastal county park with a historic spring, an observation tower, and a connection to the Pinellas Trail. Leashed dogs are welcome throughout the grounds, though they need to skip the boardwalks.', '/assets/spots/cat-park.svg', true, null, 'https://pinellas.gov/parks/wall-springs-park/', '3725 De Soto Blvd, Palm Harbor, FL 34683', 'approved'),
  ('tarpon-animal-hospital', 'Tarpon Animal Hospital', 'Vet', 'Tarpon Springs', null, 'Founded in 1954 and originally located on the Sponge Docks, this full-service dog and cat hospital is one of the area''s most established practices. Early weekday hours make drop-offs easy before work.', '/assets/spots/cat-vet.svg', true, '(727) 934-0884', 'https://tarponvet.com/', '43695 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('westlake-animal-hospital', 'Westlake Animal Hospital', 'Vet', 'Tarpon Springs', null, 'An AAHA-accredited practice that has served Tarpon Springs pets since 1976, covering wellness, surgery, and urgent care. Its sister pet resort next door handles boarding and grooming.', '/assets/spots/cat-vet.svg', true, '(727) 938-1575', 'https://www.westlakeanimalhospital.net/', '39564 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('anclote-animal-hospital', 'Anclote Animal Hospital', 'Vet', 'Tarpon Springs', null, 'A trusted neighborhood vet on Pinellas Avenue with weekday and Saturday-morning hours. A convenient option for dog owners on the south side of Tarpon Springs.', '/assets/spots/cat-vet.svg', true, '(727) 934-0814', 'https://www.ancloteanimalhospital.com/', '1840 S Pinellas Ave, Tarpon Springs, FL 34689', 'approved'),
  ('hidden-oaks-animal-hospital', 'Hidden Oaks Animal Hospital', 'Vet', 'Tarpon Springs', 'East Lake', 'A skilled small-animal practice on East Lake Road serving the eastern side of Tarpon Springs. Accepts new patients and offers online appointment requests.', '/assets/spots/cat-vet.svg', true, '(727) 942-3616', 'https://hiddenoaksanimalhospital.com/', '725 E Lake Rd N, Tarpon Springs, FL 34688', 'approved'),
  ('dockside-doggies-pet-grooming', 'Dockside Doggies Pet Grooming', 'Groomer', 'Tarpon Springs', 'Downtown Tarpon Springs', 'A full-service grooming shop on Pinellas Avenue serving Tarpon Springs and the surrounding area. Baths, haircuts, and tidy-ups with a local, personal touch.', '/assets/spots/cat-groomer.svg', true, '(727) 940-5085', null, '421 S Pinellas Ave, Tarpon Springs, FL 34689', 'approved'),
  ('the-scissor-wizard-dog-grooming', 'The Scissor Wizard Dog Grooming', 'Groomer', 'Tarpon Springs', null, 'A full-service salon grooming dogs and cats of all breeds and sizes. Known for experienced, patient groomers who handle nervous pups well.', '/assets/spots/cat-groomer.svg', true, '(727) 560-1962', null, '40347 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('westlake-animal-inn-pet-resort', 'Westlake Animal Inn Pet Resort', 'Service', 'Tarpon Springs', null, 'A boarding and grooming resort attached to Westlake Animal Hospital, so vets are steps away if your dog needs anything mid-stay. A reassuring option for longer trips.', '/assets/spots/cat-service.svg', true, '(727) 942-3691', 'https://www.westlakeanimalinn.net/', '39564 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('petco-tarpon-springs', 'Petco Tarpon Springs', 'Retail / Shop', 'Tarpon Springs', null, 'One-stop shop for food, treats, and supplies with full-service grooming, training classes, and vaccination clinics. Leashed dogs are welcome to shop along with you.', '/assets/spots/cat-shop.svg', true, '(727) 939-2937', 'https://stores.petco.com/fl/tarpon-springs/pet-supplies-tarponsprings-fl-1577.html', '40962 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('hellas-restaurant-bakery', 'Hellas Restaurant & Bakery', 'Restaurant', 'Tarpon Springs', 'Sponge Docks', 'An iconic Greek restaurant and bakery on the Sponge Docks with a limited number of designated dog-friendly patio tables — worth reserving ahead. Grab baklava to go after strolling the docks with your pup.', '/assets/spots/cat-restaurant.svg', true, '(727) 943-2400', 'https://hellasbakery.com/', '785 Dodecanese Blvd, Tarpon Springs, FL 34689', 'approved'),
  ('dock-s-waterfront', 'Dock''s Waterfront', 'Restaurant', 'Tarpon Springs', 'Sponge Docks', 'A casual waterfront bar and grill where leashed dogs join you on the umbrella-shaded patio — and even get their own dog menu. One of the most pup-pampering spots on the Anclote River.', '/assets/spots/cat-restaurant.svg', true, '(727) 935-6500', null, '210 Dodecanese Blvd, Tarpon Springs, FL 34689', 'approved'),
  ('mama-s-greek-cuisine', 'Mama''s Greek Cuisine', 'Restaurant', 'Tarpon Springs', 'Sponge Docks', 'Lively Greek dining on the Sponge Docks with a large pet-friendly outdoor patio and bar, where staff are quick with water bowls. Linger over a gyro platter while your dog people-watches.', '/assets/spots/cat-restaurant.svg', true, '(727) 944-2888', 'https://mamasgreekcuisine.net/', '735 Dodecanese Blvd, Ste 40, Tarpon Springs, FL 34689', 'approved'),
  ('tarpon-turtle-waterfront-grill', 'Tarpon Turtle Waterfront Grill', 'Restaurant', 'Tarpon Springs', 'Lake Tarpon', 'A Key West-style grill and marina on the banks of Lake Tarpon, where dogs are welcome at outdoor tables on the waterside deck. Boats, breezes, and fish and chips make it a favorite weekend outing.', '/assets/spots/cat-restaurant.svg', true, '(727) 940-5360', null, '1513 Lake Tarpon Ave, Tarpon Springs, FL 34689', 'approved'),
  ('tarpon-springs-dog-park', 'Tarpon Springs Dog Park', 'Park / Trail', 'Tarpon Springs', null, 'The city''s fenced off-leash park at the Live Oak Recreational Complex, with a separate small-dog section, agility equipment, shady oaks, and water stations. Open daily 7 a.m. to 8 p.m. with free entry.', '/assets/spots/cat-park.svg', true, '(727) 942-5610', 'https://www.ctsfl.us/facilities/facility/details/Dog-Park-6', '131 Athenian Way, Tarpon Springs, FL 34689', 'approved'),
  ('a-l-anderson-park-paw-playground', 'A.L. Anderson Park Paw Playground', 'Park / Trail', 'Tarpon Springs', null, 'A fenced off-leash area inside this 135-acre county park overlooking Salmon Bay and Lake Tarpon, with a small-dog section, benches, and plenty of mature shade trees. The rest of the park welcomes leashed dogs on its shoreline trails.', '/assets/spots/cat-park.svg', true, '(727) 943-4085', 'https://pinellas.gov/parks/a-l-anderson-park', '39699 US Highway 19 N, Tarpon Springs, FL 34689', 'approved'),
  ('fred-howard-park', 'Fred Howard Park', 'Park / Trail', 'Tarpon Springs', 'Sunset Beach', 'A 155-acre Gulf-front county park where leashed dogs can enjoy the shaded picnic areas and the scenic mile-long causeway — though the swimming beach itself is off-limits to pets. Sunset walks along the causeway with your dog are hard to beat.', '/assets/spots/cat-park.svg', true, null, 'https://pinellas.gov/parks/fred-howard-park/', '1700 Sunset Dr, Tarpon Springs, FL 34689', 'approved')
on conflict (slug) do nothing;
